#**Case Study on Testing of Hypothesis**

In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("/content/Sales_add.csv")
data

Month      Region      Manager  Sales_before_digital_add(in $)  \
0    Month-1  Region - A  Manager - A                          132921   
1    Month-2  Region - A  Manager - C                          149559   
2    Month-3  Region - B  Manager - A                          146278   
3    Month-4  Region - B  Manager - B                          152167   
4    Month-5  Region - C  Manager - B                          159525   
5    Month-6  Region - A  Manager - B                          137163   
6    Month-7  Region - C  Manager - C                          130625   
7    Month-8  Region - A  Manager - A                          131140   
8    Month-9  Region - B  Manager - C                          171259   
9   Month-10  Region - C  Manager - B                          141956   
10  Month-11  Region - B  Manager - C                          159339   
11  Month-12  Region - A  Manager - A                          178939   
12  Month-13  Region - B  Manager - A                          145062   
13  Month-14  Region - A  Manager - A                          151514   
14  Month-15  Region - C  Manager - A                          147463   
15  Month-16  Region - A  Manager - B                          177195   
16  Month-17  Region - A  Manager - C                          140862   
17  Month-18  Region - C  Manager - B                          167996   
18  Month-19  Region - B  Manager - A                          132135   
19  Month-20  Region - A  Manager - B                          152493   
20  Month-21  Region - B  Manager - A                          147425   
21  Month-22  Region - A  Manager - C                          130263   

    Sales_After_digital_add(in $)  
0                          270390  
1                          223334  
2                          244243  
3                          231808  
4                          258402  
5                          256948  
6                          222106  
7                          230637  
8                          226261  
9                          193735  
10                         203175  
11                         276279  
12                         205180  
13                         253131  
14                         229336  
15                         187305  
16                         234908  
17                         191517  
18                         227040  
19                         212579  
20                         263388  
21                         243020

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   Month                           22 non-null     object
 1   Region                          22 non-null     object
 2   Manager                         22 non-null     object
 3   Sales_before_digital_add(in $)  22 non-null     int64 
 4   Sales_After_digital_add(in $)   22 non-null     int64 
dtypes: int64(2), object(3)
memory usage: 1008.0+ bytes


A company started to invest in digital marketing as a new way of their product
promotions. For that they collected data and decided to carry out a study on it.

● The company wishes to clarify whether there is any increase in sales after
stepping into digital marketing.

● The company needs to check whether there is any dependency between
thefeatures “Region” and “Manager”.

Help the company to carry out their study with the help of data provided.

**To check whether there is any increase in sales after stepping into digital marketing**

Here we use ttest, because the size of the sample is less than 30 and population variance is unknown.

And we want to compare sales before and after stepping into digital marketing across all months, so paired ttest is used (ttest_rel).

Null Hypothesis (H0): There is no increase in sales after stepping into digital marketing.

Alternative Hypothesis (H1): There is an increase in sales after stepping into digital marketing.


In [4]:
# Define the Hypothesis

Null="There is no increase in sales after stepping into digital marketing."
Alt="There is an increase in sales after stepping into digital marketing."

In [5]:
# Importing ttest_rel from scipy
from scipy.stats import ttest_rel

In [6]:
# Compute t statistic and p value
t_stat,p_value = ttest_rel(data['Sales_before_digital_add(in $)'],data['Sales_After_digital_add(in $)'])

In [7]:
print(t_stat,p_value)

-12.09070525287017 6.336667004575778e-11


In [8]:
# Print result of Hypothesis testing
# significance level is 5%.

if p_value<0.05 :
  print('Reject Null Hypothesis', '\n', 'ie.,', Alt)
else:
  print('Accept Null Hypothesis', '\n', Null)

Reject Null Hypothesis 
 ie., There is an increase in sales after stepping into digital marketing.


**To check whether there is any dependency between the features “Region” and “Manager”.**

In [9]:
# Chi-Square test of independence is used to check the depedency between the features.

from scipy.stats import chi2_contingency

Null Hypothesis (H0): There is no dependency between the "Region" and "Manager" features.

Alternative Hypothesis (H1): There is a dependency between the "Region" and "Manager" features.

In [10]:
# Define the Hypothesis

H0="There is no dependency between the Region and Manager features."
H1="There is a dependency between the Region and Manager features."

In [11]:
#The Dependency Analysis between the variables region and manager

table_data=pd.crosstab([data['Region']],[data['Manager']])
table_data

Manager     Manager - A  Manager - B  Manager - C
Region                                           
Region - A            4            3            3
Region - B            4            1            2
Region - C            1            3            1

In [12]:
#Chi square test of independence

chi_stat,p_value,dof,expected=chi2_contingency(table_data)

In [13]:
print( "chi-Square statistic - ",chi_stat,'\n',"P Value - ",p_value,'\n','Degrees of freedom : ',dof,'\n','Expected Freq','\n',expected)

chi-Square statistic -  3.050566893424036 
 P Value -  0.5493991051158094 
 Degrees of freedom :  4 
 Expected Freq 
 [[4.09090909 3.18181818 2.72727273]
 [2.86363636 2.22727273 1.90909091]
 [2.04545455 1.59090909 1.36363636]]


In [14]:
# Print the results

if p_value<0.05:
  print("Reject Null Hypothesis",'\n','ie.,',H1)
else:
  print("Accept Null Hypothesis",'\n','ie.,',H0)

Accept Null Hypothesis 
 ie., There is no dependency between the Region and Manager features.
